project:
  type: website
  output-dir: docs

website:
  title: "魔狸"
  favicon: favicon.svg
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/TanukiMa
      - icon: twitter
        href: https://twitter.com/Matanuki
  google-analytics: "UA-457627174"
format:
  html:
    theme: journal
    css: styles.css
