---
title: "quarto"
format:
  html:
    toc: true
lang: ja
author: "魔狸"
date: "2024-09-09"
categories: [Windows,MacOS,winget,homebrew]
filters:
  - social-share
share:
  permalink: "https://TanukiMa.github.io/posts/2024/09/quarto.html"
  description: "「quarto」"
  twitter: true
  mastodon: true

---
色々な文書を作成する機会が多いです。

正直、辟易としています。

昭和のガリ版印刷を引きずったような汚いフォント、歪んだ罫線、構成力も校正力も欠けている文章。

PDF化されているのに、印刷して記入して、スキャンして取り込む？

そんな不思議なことが平然とまかり通っているのが、日本の医療の現場です。

医療の情報化を通じて効率化を推進していきたいと常々考えています。

# Mermaid で Gantt chart

```{mermaid}
gantt
    title A Gantt Diagram
    dateFormat YYYY-MM-DD
    section Section
        A task          :a1, 2014-01-01, 30d
        Another task    :after a1, 20d
    section Another
        Task in Another :2014-01-12, 12d
        another task    :24d
```
<!--
# Mermaid で 

```{mermaid}
---
title: 不安定狭心症/NSTEMIへのアプローチ
---
flowchart TD
    A[低リスク] --> B(アスピリン、
    P2Y<sub>12</sub>阻害薬：クロピドグレル、チカグレロル
    抗凝固薬：エノキサバリン、フォンダバリヌクス、UFH)
    C[高リスク] --> D(アスピリン、
    P2Y<sub>12</sub>阻害薬：チカグレロル（ or クロピドグレル）、
    抗凝固薬：UFH、エノキサバリン、bivalirudin±GPIIb/IIIa阻害薬)
    D --> F[侵襲的戦略]
    B --> E[保存的戦略]
    F --> G[血管造影]
    E --> |繰り返す虚血発作| X((( ))) -->|±GPIIb/IIIa阻害薬| G
    style X fill:#ffffff,stroke:#ffffff
    E --> H[血行動態が安定したら
    退院前に負荷試験]
    G --> I[CABG]
    G --> J[PCI]
    J --> K[長期薬物療法]
    I --> K
    G --> L[薬物療法]
    L --> K
    H --> |低リスク| N[薬物療法]
    H --> |高リスク| G 
```
-->

<!--
```{mermaid}
architecture-beta
    group api(cloud)[API]

    service db(database)[Database] in api
    service disk1(disk)[Storage] in api
    service disk2(disk)[Storage] in api
    service server(server)[Server] in api

    db:L -- R:server
    disk1:T -- B:server
    disk2:T -- B:db
```
-->
