---
title: "おれは ねむれないんだ"
format:
  html:
    toc: true
lang: ja
author: "Ma, Tanuki"
date: "2025-01-03"
categories: [医療]
filters:
  - social-share
share:
  permalink: "https://TanukiMa.github.io/posts/2024/09/cantsleep.html"
  description: "「おれは ねむれないんだ」"
  twitter: true
  mastodon: true
---
以下は
以前に日本アンチジェネリック医薬品学会に寄稿したものです。

----

ぼくは ばすえのびょういんで とうちょくというなの ひごうほうなやきんに じゅうじさせられていました。

あるばん 「このひと、ろじょうでねていた！」としんせつなわかものが みなりのよろしくないおとこを びょういんにつれてきました。

しかし、しんせつなわかものは みなりのよろしくないおとこを びょういんにおきざりにして かえってしまいました。

ねむりこけていた みなりのよろしくないおとこは がばりとおきあがり、ぼくにむかって さけびました。

**「おれは ねむれないんだ！」**

はぁ？とぼくは おもいました。さきほどまで ろじょうで じゅくすいされていたのですよね？

おとこは さけびました。

「くすりをだせ！くすりを！」

ぼくは だまっていました。

つづけて おとこは さけびました。

「ねむれるくすりといったら ネスゲン だろう！ネスゲンをだせ！ ネスゲンを！」

そのなまえのくすりは びょういんで さいようしていませんでした。

ぼくは しょうじきに こたえました。

「そのようななまえのくすりは ありません」

おとこは おこりだしました。

「にーちゃん わかってるだろぉ おれはシャブやってるんだよぉ おまえなんか さすのは こわくないんだぞぉ」

ぼくは あとずさりしました。

つづけて おとこは どなりました

「セレナミン をだせ、セレナミンを！」

そのなまえのくすりは びょういんでさいようしていませんでした。

ぼくは しょうじきに こたえました。

「そのようななまえのくすりは ありません」

おとこは さらにおこりました。

「にーちゃん さされたいのかぁ？」

ぼくは あとずさりしました。

つづけて おとこは どなりました

「ユーパン をだせ、ユーパンを！」

そのなまえのくすりは びょういんでさいようしていませんでした。

ぼくは しょうじきに こたえました。

「そのようななまえのくすりは ありません」

おとこは さらにおこりました。

「にーちゃん さされたいのかぁ？」

ぼくは あとずさりしました。

しかし うしろは かべでした。ひやあせが でてきました。

ぼくと おとこのあいだには ちんもくしたじかんと きまずいふんいきが ただよいました。

おとこは
「ちぇっ！つかえない びょういんだな！どこにでもある くすりがないなんて！」
と どなって おかえりになられました。

病院では先発医薬品しか採用していなかったので、薬物中毒者に更に薬物を処方する禁忌を避けることができました。

ジェネリック医薬品が普及したおかげで、医師として正しい行動を取ることができ、命が救われました。

おとこは じぶんのいえのじゅうしょをかいて うけつけしていたので、せいぎかんあふれる ぼくは けいさつに つうほうしました。

ごじつ かくせいざい しょじ と しよう のようぎで たいほされたと しんぶんにのっていました。

めでたしめでたし。
